name = "AMZolaTheme"
description = "A Zola theme"
license = "MIT"
homepage = "https://github.com/jel1yspot/am-zola-theme"
tags = ["blog", "minimal"]

[extra]
tag_colors = ["#c98732", "#e85a4f", "#48a3d8", "#8f6bd8", "#2fbf71", "#f2b94e"]

[extra.languages.en]
date_format = "%B %d, %Y"
home = "Home"
pin_pages = "Pin pages"
blog = "Blog"
tags = "Tags"
recent = "Recent"
recent_updates = "Recent Updates"
posts_count = "Posts"
view_all = "View All"
tag_count_format = "{} posts"
pagination_prev = "Prev"
pagination_next = "Next"
search = "Search"
language = "Language"
dark_mode = "Dark mode"
light_mode = "Light mode"
taxonomy_title_format = "{taxonomy}: {term}"

[extra.languages.zh]
date_format = "%Y 年 %m 月 %d 日"
home = "首页"
pin_pages = "置顶文章"
section = "类别"
taxonomies = "分类"
blog = "博客"
music = "音乐"
tags = "标签"
recent_updates = "最近更新"
posts_count = "篇文章"
view_all = "查看全部"
tag_count_format = "{} 篇文章"
pagination_prev = "上一页"
pagination_next = "下一页"
recent = "最近"
search = "搜索"
language = "语言"
dark_mode = "深色模式"
light_mode = "浅色模式"
taxonomy_title_format = "{taxonomy}：{term}"
